### ISSUE TITLE
Speed up Startup Procedure inside the ClassFinder

### ISSUE THREAD

**Issue by N520** [FHOOEAIST/seshat#6]
**Is your feature request related to a problem? Please describe.**
Seshat always checks all classes on the file path, which makes it excruciatingly slow during startup. Depending on the project, this can take up to a minute, especially when using spring boot, due to a large number of dependencies.

**Describe the solution you'd like**
I would like to see some optimization during the startup procedure, specifically inside the `ClassFinder`. Maybe some parallelization could help out?

**Describe alternatives you've considered**
Usually, logging frameworks use their implementation and thus, don't need to scan for implementations. Arguably, this is a KO criterium for using Seshat during development. 

**Additional context**
Tried it both in a Spring Boot Java 11 context, as well as in a Scala context. The latter was a bit quicker to initialise, the former was, sadly, quite slow. This effect is increased drastically when debugging

**OPTIONAL Priority**
Major

**Comment by oliver-krauss** [comment]
I'd go a step further and say that https://github.com/FHOOEAIST/seshat/blob/db0c6fffc84771df829c5e509866ca22fcabedac/api/src/main/java/science/aist/seshat/Logger.java#L55 is wrong and should not be referencing the AbstractLoggerFactory which per default executes really slow code.

Posible solution would be similar to how slf4j handles it - via a user-provided path (but not to the logger - the logger factory)
https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java/org/slf4j/LoggerFactory.java

Speedups in ClassFinder -> Parallelism yes; but also requiring specific package names or class names so not EVERY class in the path has to be searched (which are an insane amount)

**Comment by oliver-krauss** [comment]
Maybe a 3 pronged approach:
- 1st look for a config file in the execution directory
- 2nd look for a system setting (like seshat.loglevel)
- 3rd use the AbstractLoggerFactory with the restrictions described above.

The order is from most specific to generic (1 - 2) and with a backup that allows convention over configuraiton (3)
